// <auto-generated />
using System;
using GinPair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GinPair.Migrations
{
    [DbContext(typeof(GinPairDbContext))]
    [Migration("20241209212920_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gp_schema")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GinPair.Models.LifeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("When")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("when");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", "gp_schema");
                });

            modelBuilder.Entity("GinPair.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_metas");

                    b.ToTable("metas", "gp_schema");
                });

            modelBuilder.Entity("GinPair.Models.Tonic", b =>
                {
                    b.Property<int>("TonicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tonic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TonicId"));

                    b.Property<string>("TonicBrand")
                        .HasColumnType("text")
                        .HasColumnName("tonic_brand");

                    b.Property<string>("TonicFlavour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tonic_flavour");

                    b.HasKey("TonicId")
                        .HasName("pk_tonics");

                    b.ToTable("tonics", "gp_schema");
                });
#pragma warning restore 612, 618
        }
    }
}
