// <auto-generated />
using System;
using GinPair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GinPair.Migrations;

[DbContext(typeof(GinPairDbContext))]
[Migration("20241214181214_tonicSeedData")]
partial class tonicSeedData
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("gp_schema")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GinPair.Models.Gin", b =>
            {
                b.Property<int>("GinId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("gin_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GinId"));

                b.Property<string>("Distillery")
                    .HasMaxLength(100)
                    .HasColumnType("varchar")
                    .HasColumnName("distillery");

                b.Property<string>("GinDescription")
                    .HasMaxLength(500)
                    .HasColumnType("varchar")
                    .HasColumnName("gin_description");

                b.Property<string>("GinName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar")
                    .HasColumnName("gin_name");

                b.HasKey("GinId")
                    .HasName("pk_gins");

                b.ToTable("gins", "gp_schema");
            });

        modelBuilder.Entity("GinPair.Models.LifeEvent", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("EventName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("event_name");

                b.Property<int>("Type")
                    .HasColumnType("integer")
                    .HasColumnName("type");

                b.Property<DateTime>("When")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("when");

                b.HasKey("Id")
                    .HasName("pk_events");

                b.ToTable("events", "gp_schema");
            });

        modelBuilder.Entity("GinPair.Models.Meta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.HasKey("Id")
                    .HasName("pk_metas");

                b.ToTable("metas", "gp_schema");
            });

        modelBuilder.Entity("GinPair.Models.Pairing", b =>
            {
                b.Property<int>("PairingId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("pairing_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairingId"));

                b.Property<int>("PairedGinGinId")
                    .HasColumnType("integer")
                    .HasColumnName("paired_gin_gin_id");

                b.Property<int>("PairedTonicTonicId")
                    .HasColumnType("integer")
                    .HasColumnName("paired_tonic_tonic_id");

                b.HasKey("PairingId")
                    .HasName("pk_pairings");

                b.HasIndex("PairedGinGinId")
                    .HasDatabaseName("ix_pairings_paired_gin_gin_id");

                b.HasIndex("PairedTonicTonicId")
                    .HasDatabaseName("ix_pairings_paired_tonic_tonic_id");

                b.ToTable("pairings", "gp_schema");
            });

        modelBuilder.Entity("GinPair.Models.Tonic", b =>
            {
                b.Property<int>("TonicId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("tonic_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TonicId"));

                b.Property<string>("TonicBrand")
                    .HasMaxLength(100)
                    .HasColumnType("varchar")
                    .HasColumnName("tonic_brand");

                b.Property<string>("TonicFlavour")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar")
                    .HasColumnName("tonic_flavour");

                b.HasKey("TonicId")
                    .HasName("pk_tonics");

                b.ToTable("tonics", "gp_schema");

                b.HasData(
                    new
                    {
                        TonicId = 1,
                        TonicBrand = "FeverTree",
                        TonicFlavour = "Indian"
                    },
                    new
                    {
                        TonicId = 2,
                        TonicBrand = "FeverTree",
                        TonicFlavour = "Light"
                    },
                    new
                    {
                        TonicId = 3,
                        TonicBrand = "FeverTree",
                        TonicFlavour = "Mediterranean"
                    },
                    new
                    {
                        TonicId = 4,
                        TonicBrand = "FeverTree",
                        TonicFlavour = "ElderFlower"
                    },
                    new
                    {
                        TonicId = 5,
                        TonicBrand = "FeverTree",
                        TonicFlavour = "Aromatic"
                    });
            });

        modelBuilder.Entity("GinPair.Models.Pairing", b =>
            {
                b.HasOne("GinPair.Models.Gin", "PairedGin")
                    .WithMany()
                    .HasForeignKey("PairedGinGinId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_pairings_gins_paired_gin_gin_id");

                b.HasOne("GinPair.Models.Tonic", "PairedTonic")
                    .WithMany()
                    .HasForeignKey("PairedTonicTonicId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_pairings_tonics_paired_tonic_tonic_id");

                b.Navigation("PairedGin");

                b.Navigation("PairedTonic");
            });
#pragma warning restore 612, 618
    }
}
