// <auto-generated />
using GinPair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GinPair.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(GinPairDbContext))]
    [Migration("20250520212351_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gp_schema")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GinPair.Models.Gin", b =>
                {
                    b.Property<int>("GinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GinId"));

                    b.Property<string>("Distillery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GinDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GinId");

                    b.ToTable("Gins", "gp_schema");

                    b.HasData(
                        new
                        {
                            GinId = 1,
                            Distillery = "Whitley Neill",
                            GinName = "Rhubarb & Ginger"
                        },
                        new
                        {
                            GinId = 2,
                            Distillery = "Whitley Neill",
                            GinName = "Blood Orange"
                        },
                        new
                        {
                            GinId = 3,
                            Distillery = "Caorunn",
                            GinName = "Scottish Raspberry"
                        },
                        new
                        {
                            GinId = 4,
                            Distillery = "Skylark",
                            GinName = "Lantic"
                        });
                });

            modelBuilder.Entity("GinPair.Models.Pairing", b =>
                {
                    b.Property<int>("PairingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PairingId"));

                    b.Property<int>("GinId")
                        .HasColumnType("int");

                    b.Property<int>("TonicId")
                        .HasColumnType("int");

                    b.HasKey("PairingId");

                    b.HasIndex("GinId");

                    b.HasIndex("TonicId");

                    b.ToTable("Pairings", "gp_schema");

                    b.HasData(
                        new
                        {
                            PairingId = 1,
                            GinId = 1,
                            TonicId = 4
                        },
                        new
                        {
                            PairingId = 2,
                            GinId = 2,
                            TonicId = 3
                        },
                        new
                        {
                            PairingId = 3,
                            GinId = 3,
                            TonicId = 3
                        },
                        new
                        {
                            PairingId = 4,
                            GinId = 4,
                            TonicId = 2
                        });
                });

            modelBuilder.Entity("GinPair.Models.Tonic", b =>
                {
                    b.Property<int>("TonicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TonicId"));

                    b.Property<string>("TonicBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TonicFlavour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TonicId");

                    b.ToTable("Tonics", "gp_schema");

                    b.HasData(
                        new
                        {
                            TonicId = 1,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Indian"
                        },
                        new
                        {
                            TonicId = 2,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Light"
                        },
                        new
                        {
                            TonicId = 3,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Mediterranean"
                        },
                        new
                        {
                            TonicId = 4,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "ElderFlower"
                        },
                        new
                        {
                            TonicId = 5,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Aromatic"
                        });
                });

            modelBuilder.Entity("GinPair.Models.Pairing", b =>
                {
                    b.HasOne("GinPair.Models.Gin", "PairedGin")
                        .WithMany("Pairings")
                        .HasForeignKey("GinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GinPair.Models.Tonic", "PairedTonic")
                        .WithMany("Pairings")
                        .HasForeignKey("TonicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PairedGin");

                    b.Navigation("PairedTonic");
                });

            modelBuilder.Entity("GinPair.Models.Gin", b =>
                {
                    b.Navigation("Pairings");
                });

            modelBuilder.Entity("GinPair.Models.Tonic", b =>
                {
                    b.Navigation("Pairings");
                });
#pragma warning restore 612, 618
        }
    }
}
