// <auto-generated />
using GinPair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GinPair.Migrations.Postgres.Migrations
{
    [DbContext(typeof(GinPairDbContext))]
    [Migration("20250520210717_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gp_schema")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GinPair.Models.Gin", b =>
                {
                    b.Property<int>("GinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gin_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GinId"));

                    b.Property<string>("Distillery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distillery");

                    b.Property<string>("GinDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("gin_description");

                    b.Property<string>("GinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gin_name");

                    b.HasKey("GinId")
                        .HasName("pk_gins");

                    b.ToTable("gins", "gp_schema");

                    b.HasData(
                        new
                        {
                            GinId = 1,
                            Distillery = "Whitley Neill",
                            GinName = "Rhubarb & Ginger"
                        },
                        new
                        {
                            GinId = 2,
                            Distillery = "Whitley Neill",
                            GinName = "Blood Orange"
                        },
                        new
                        {
                            GinId = 3,
                            Distillery = "Caorunn",
                            GinName = "Scottish Raspberry"
                        },
                        new
                        {
                            GinId = 4,
                            Distillery = "Skylark",
                            GinName = "Lantic"
                        });
                });

            modelBuilder.Entity("GinPair.Models.Pairing", b =>
                {
                    b.Property<int>("PairingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pairing_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PairingId"));

                    b.Property<int>("GinId")
                        .HasColumnType("integer")
                        .HasColumnName("gin_id");

                    b.Property<int>("TonicId")
                        .HasColumnType("integer")
                        .HasColumnName("tonic_id");

                    b.HasKey("PairingId")
                        .HasName("pk_pairings");

                    b.HasIndex("GinId")
                        .HasDatabaseName("ix_pairings_gin_id");

                    b.HasIndex("TonicId")
                        .HasDatabaseName("ix_pairings_tonic_id");

                    b.ToTable("pairings", "gp_schema");

                    b.HasData(
                        new
                        {
                            PairingId = 1,
                            GinId = 1,
                            TonicId = 4
                        },
                        new
                        {
                            PairingId = 2,
                            GinId = 2,
                            TonicId = 3
                        },
                        new
                        {
                            PairingId = 3,
                            GinId = 3,
                            TonicId = 3
                        },
                        new
                        {
                            PairingId = 4,
                            GinId = 4,
                            TonicId = 2
                        });
                });

            modelBuilder.Entity("GinPair.Models.Tonic", b =>
                {
                    b.Property<int>("TonicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tonic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TonicId"));

                    b.Property<string>("TonicBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tonic_brand");

                    b.Property<string>("TonicFlavour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tonic_flavour");

                    b.HasKey("TonicId")
                        .HasName("pk_tonics");

                    b.ToTable("tonics", "gp_schema");

                    b.HasData(
                        new
                        {
                            TonicId = 1,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Indian"
                        },
                        new
                        {
                            TonicId = 2,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Light"
                        },
                        new
                        {
                            TonicId = 3,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Mediterranean"
                        },
                        new
                        {
                            TonicId = 4,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "ElderFlower"
                        },
                        new
                        {
                            TonicId = 5,
                            TonicBrand = "FeverTree",
                            TonicFlavour = "Aromatic"
                        });
                });

            modelBuilder.Entity("GinPair.Models.Pairing", b =>
                {
                    b.HasOne("GinPair.Models.Gin", "PairedGin")
                        .WithMany("Pairings")
                        .HasForeignKey("GinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pairings_gins_gin_id");

                    b.HasOne("GinPair.Models.Tonic", "PairedTonic")
                        .WithMany("Pairings")
                        .HasForeignKey("TonicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pairings_tonics_tonic_id");

                    b.Navigation("PairedGin");

                    b.Navigation("PairedTonic");
                });

            modelBuilder.Entity("GinPair.Models.Gin", b =>
                {
                    b.Navigation("Pairings");
                });

            modelBuilder.Entity("GinPair.Models.Tonic", b =>
                {
                    b.Navigation("Pairings");
                });
#pragma warning restore 612, 618
        }
    }
}
